require("gloria.plugins-setup")
require("gloria.core.options")
require("gloria.core.keymaps")
require("gloria.core.colorscheme")
require("gloria.plugins.comment")
require("gloria.plugins.nvim-tree")
require("gloria.plugins.lualine")
require("gloria.plugins.telescope") 
require("gloria.plugins.nvim-cmp")
require("gloria.plugins.lsp.mason")
require("gloria.plugins.lsp.lspsaga")
require("gloria.plugins.lsp.lspconfig")
require("gloria.plugins.autopairs")
require("gloria.plugins.treesitter")
require("gloria.plugins.gitsigns")
require("gloria.plugins.vimtex")
require("gloria.plugins.luasnip")

